# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://unclepi.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Uncle Pi
user_description: 先别看aboutme,还没改
user_title: 皮叔
email: zq.feng@outlook.com
twitter_username: fengzhengquan
github_username:  simfeng
gplus_username:  zhengquan Feng
disqus_username: unclepipi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
